import React, { useState, useEffect } from 'react';
import Grid from '@mui/material/Grid';
import { Box, Link, Typography } from '@mui/material';

import Container from '@mui/material/Container';

function Copyright(props) {
    return (
        <Box variant="body2" color="text.secondary" align="center" {...props}>
            {`© Copyright ${new Date().getFullYear()} `}
            <Link color="inherit" href="https://askmediatech.com/">
                AskMediaTech.
            </Link>{' '}
            {' All rights reserved.'}
        </Box>
    );
}

const footers = [
    {
        title: 'AskMediaTech',
        description: [
            'The AskMediaTech platform provides services, tools, and information generated by AI tools. We provide top-tech innovations to accelerate digital services.'
        ]
    },
    {
        title: 'Company',
        description: ['About Us', 'Contact Us', 'Explore Things', /* 'Our Group', 'Our Partners' */]
    },
    {
        title: 'Resources',
        description: ['Services', 'Sitemap', 'FAQs']
    },
    {
        title: 'Legal',
        description: ['Privacy Policy', 'Terms & Conditions', ' Cookie Policy']
    }
];

const preventDefault = (event) => event.preventDefault();

function MinimalFooter() {
    return (
        <Box
            sx={{
                display: 'flex',
                flexWrap: 'wrap',
                justifyContent: 'center',
                variant: 'body2',
                '& > :not(style) ~ :not(style)': {
                    ml: 1,
                },
            }}
            onClick={preventDefault}
        >
            <Link color="inherit" href="#" underline="hover" to={`/sitemap}`}>
                {'Sitemap |'}
            </Link>
            <Link color="inherit" href="#" underline="hover">
                {'Privacy Policy |'}
            </Link>
            <Link color="inherit" href="#" underline="hover">
                {'Terms'}
            </Link>
        </Box>
    );
}


export default function Footer() {
    const [footerInfo, setFooters] = useState([]);

    useEffect(() => {
        setFooters(footers);
    }, []);
    return (
        <>
            <Container
                maxWidth="md"
                component="footer"
                sx={{
                    borderTop: (theme) => `1px solid ${theme.palette.divider}`,
                    mt: 8,
                    my: '200px',
                    py: [3, 6]
                }}
            >
                {/* <Grid container spacing={4} justifyContent="space-evenly">
                    {footerInfo.map((footer) => (
                        <Grid item xs={6} sm={3} key={footer.title}>
                            <Typography variant="subtitle1" color="text.primary" gutterBottom>
                                {footer.title}
                            </Typography>
                            <Box component="ul" sx={{ listStyle: 'none' }}>
                                {footer.description.map((item) => (
                                    <Box component="li" key={item} sx={{ textAlign: 'left' }}>
                                        <Link
                                            href="#"
                                            variant="body2"
                                            color="text.secondary"
                                            underline={footer.description.length == 1 ? 'none' : 'hover'}
                                        >
                                            {item}
                                        </Link>
                                    </Box>
                                ))}
                            </Box>
                        </Grid>
                    ))}
                </Grid>
                 */}
                <Grid
                    container
                    spacing={1}
                    direction="column"
                    alignItems="center"
                    justifyContent="center">
                    <Copyright sx={{ mr: 1 }} />
                    <MinimalFooter />
                </Grid>

            </Container>
        </>
    );
}
