import React, { useState, useEffect } from 'react';
import { NavLink, Link, matchPath, useLocation, Outlet, useParams } from 'react-router-dom';

import { useSelector, useDispatch } from 'react-redux';

import { Avatar, Button, Card, CardActions, CardContent, CardMedia, Grid, Typography } from '@mui/material';
import VideoSettingsIcon from '@mui/icons-material/VideoSettings';


import CssBaseline from '@mui/material/CssBaseline';
import Container from '@mui/material/Container';
import { createTheme, ThemeProvider } from '@mui/material/styles';

import withHeaderFooterLayout from '@/hoc/withHeaderFooterLayout';
import { service_items } from '@/menu-items/service_items';

const home_content = {
    headline: `Who We Are and What Are We Doing?`,
    content: `The AskMediaTech platform provides services, tools, and information generated by AI tools. 
    We work to create innovative,  world-first experiences for Accelerating technology.
    We provide top-tech innovations to accelerate digital services.`
};

const defaultTheme = createTheme();

function Home() {
    const [serviceItems, setServiceItems] = useState([]);

    useEffect(() => {
        setServiceItems(service_items);
    }, []);

    useEffect(() => {

    });

    return (
        <ThemeProvider theme={defaultTheme}>
            <CssBaseline />
            <main>
                {/* <CardMedia
                component="div"
                sx={{
                    // 16:9
                    pt: '56.25%',
                }}
                image="https://source.unsplash.com/random?wallpapers"
            /> */}
                <Container sx={{ py: 8 }}>
                    <Grid container spacing={2}>
                        {serviceItems &&
                            serviceItems.map((item, index) => (
                                <Grid item key={index} xs={12} sm={6} md={4}>
                                    <Card sx={{ 
                                        backgroundColor: '#e3f2fd', height: '100%', display: 'flex', flexDirection: 'column',
                                    '&:hover': {
                                        backgroundColor: '#fff',
                                        color: 'red',
                                        border: 1,
                                        borderColor: '#e3f2fd'
                                    }
                                }}>
                                        <NavLink
                                            style={{ color: 'inherit', textDecoration: 'inherit' }}
                                            to={`/services/${item.link}`}
                                            state={`From Page`}
                                        >
                                            <Typography variant="h5" align="center" color="text.primary" gutterBottom>
                                                {item.title}
                                            </Typography>

                                            <CardMedia component="div" align="center" sx={{ pt: '10.25%' }} >
                                                {item.image()}
                                            </CardMedia>

                                            <CardContent align="center" sx={{ flexGrow: 1 }}>
                                                <Typography color="text.secondary">{item.description}</Typography>
                                            </CardContent>
                                        </NavLink>
                                    </Card>
                                </Grid>
                            ))}
                    </Grid>
                </Container>
            </main>
        </ThemeProvider>
    );
}

const HomePageLayout = withHeaderFooterLayout(Home, home_content);

export default HomePageLayout;
